import './globals.css'
import { Vazirmatn } from 'next/font/google'
const vazirFont = Vazirmatn({ subsets: ['arabic'] })

export const metadata = {
  title: 'Online Shopping Menu',
  description: 'Generated by Bahar Keshavarz' ,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={vazirFont.className}>{children}</body>
    </html>
  )
}
